/**
 * Status effects the interaction rules use. Durations are the wiki values decided in
 * docs/research/*.md (state after the Combat Style Modernisation, March 2026).
 */
import { BuffDef } from './rules-model';

const W = 'https://runescape.wiki/w/';

export const BUFFS: BuffDef[] = [
  // ---------------------------------------------------------------- stacks / resources (no timer: stay until consumed)
  { id: 'bloodlust', name: 'Bloodlust', kind: 'Buff', on: 'self', durationTicks: null, stacks: { max: 4 }, wikiId: 1453,
    text: 'Melee basics grant 1 (Rend 2), max 4 – 8 during Berserk with 2 per basic. 4 stacks empower Assault, Hurricane, Flurry and Greater Flurry. No timer.', source: W + 'Bloodlust' },
  { id: 'necrosis', name: 'Necrosis', kind: 'Buff', on: 'self', durationTicks: null, stacks: { max: 12 }, wikiId: 48333,
    text: 'Touch of Death +4 (basic attack +2 during Living Death), max 12. Finger of Death costs 10% less per stack (up to 6) and consumes them; Death Grasp deals extra damage per stack. No timer.', source: W + 'Necrosis' },
  { id: 'residual-souls', name: 'Residual Souls', kind: 'Buff', on: 'self', durationTicks: null, stacks: { max: 3 }, wikiId: 48334,
    text: 'Soul Sap +1 per target hit, max 3 (5 with the Soulbound lantern). Soul Strike uses 1, Volley of Souls fires one hit per stack and consumes all. No timer.', source: W + 'Residual_Soul' },
  { id: 'storm-shards', name: 'Storm Shards', kind: 'Buff', on: 'self', durationTicks: null, stacks: { max: 10 }, wikiId: 14675,
    text: 'Storm Shards adds 1 per hit, max 10. Shatter consumes all of them for its damage. No timer.', source: W + 'Storm_Shards' },
  { id: 'soul-reave', name: 'Soul Reave', kind: 'Buff', on: 'self', durationTicks: null, stacks: { max: 4 }, wikiId: 52064,
    text: "Devourer's Guard: basic attacks add 1; at 4 the next basic attack is empowered and grants a Residual Soul.", source: W + 'Soul_Reave' },
  { id: 'valour', name: 'Valour', kind: 'Buff', on: 'self', durationTicks: null, stacks: { max: 25 },
    text: 'The Phantom Guardian gains 1 per hit you take, max 25; Command Phantom Guardian consumes them. No timer.', source: W + 'Valour' },
  { id: 'glacial-embrace', name: 'Glacial Embrace', kind: 'Buff', on: 'self', durationTicks: null, stacks: { max: 10 },
    text: 'Stacking magic resource (Wen). No timer.', source: W + 'Glacial_Embrace' },
  { id: 'essence-corruption', name: 'Essence Corruption', kind: 'Buff', on: 'self', durationTicks: null, stacks: { max: 10 },
    text: 'Stacking magic resource. No timer.', source: W + 'Essence_Corruption' },

  // ---------------------------------------------------------------- generic
  { id: 'stunned', name: 'Stunned', kind: 'Debuff', on: 'target', durationTicks: 3, text: 'Target cannot act.', source: W + 'Stun' },
  { id: 'bound', name: 'Bound', kind: 'Debuff', on: 'target', durationTicks: 10, text: 'Target cannot move.', source: W + 'Bind' },

  // ---------------------------------------------------------------- melee
  { id: 'berserk', name: 'Berserk', kind: 'Buff', on: 'self', durationTicks: 33, wikiId: 14707,
    text: 'Melee attacks deal 1.75x damage (bleeds excluded), damage taken +25%. Bloodlust cap 8 and basics grant 2 stacks. Overpower cooldown 15 ticks.', source: W + 'Berserk' },
  { id: 'greater-fury', name: 'Greater Fury', kind: 'Buff', on: 'self', durationTicks: 25, wikiId: 49534, crit: { add: 1, style: 'Melee', firstHitOnly: true },
    text: 'Next non-bleed melee hit is a guaranteed critical strike (first hit of a channel, one hit of a multi-hit).', source: W + 'Greater_Fury' },
  { id: 'fury', name: 'Fury', kind: 'Buff', on: 'self', durationTicks: 25, crit: { add: 0.25, style: 'Melee', firstHitOnly: true },
    text: 'Next melee attack +25% critical strike chance (the wiki states no duration; 25 ticks assumed like Greater Fury).', source: W + 'Fury' },
  { id: 'chaos-roar', name: 'Chaos Roar', kind: 'Buff', on: 'self', durationTicks: 12, wikiId: 46279,
    text: 'Next damaging melee ability within 12 ticks deals 1.75x base damage (all hits of multi-hits, first hit of channels, bleeds included).', source: W + 'Chaos_Roar' },
  { id: 'endless-assault', name: 'Endless Assault', kind: 'Buff', on: 'self', durationTicks: 10, wikiId: 40938,
    text: 'Next Assault, Flurry or Greater Flurry is dealt as an un-cancellable damage over time with normal hit timing; other abilities can be used meanwhile.', source: W + 'Endless_Assault' },
  { id: 'dismember', name: 'Dismember', kind: 'Debuff', on: 'target', durationTicks: 16, wikiId: 44244,
    text: 'Bleed: 8 hits of 25–35% every 2 ticks. Recasting refreshes it. Removed by Freedom.', source: W + 'Dismember' },
  { id: 'slaughter', name: 'Slaughter', kind: 'Debuff', on: 'target', durationTicks: 18, wikiId: 14683,
    text: 'Bleed: 6 hits every 3 ticks. Coexists with Dismember and Massacre.', source: W + 'Slaughter' },
  { id: 'massacre', name: 'Massacre', kind: 'Debuff', on: 'target', durationTicks: 25, wikiId: 14687,
    text: 'Bleed: 6 hits every 4 ticks after the direct hit.', source: W + 'Massacre' },
  { id: 'meteor-strike', name: 'Meteor Strike', kind: 'Buff', on: 'self', durationTicks: 50, wikiId: 52776, adrenalinePerTick: 4.5, adrenalinePerTickStyle: 'Melee',
    text: '+4.5% adrenaline per tick with a melee weapon; melee basic abilities generate 1.5x adrenaline. Recasting refreshes it.', source: W + 'Meteor_Strike' },
  { id: 'pulverise', name: 'Pulverise', kind: 'Debuff', on: 'target', durationTicks: 50, wikiId: 51665,
    text: 'Target deals 25% less damage for 50 ticks.', source: W + 'Pulverise' },
  { id: 'enduring-ruin', name: 'Enduring Ruin (gloves of passage)', kind: 'Buff', on: 'self', durationTicks: 10,
    text: 'Next melee attack within 6 s deals +10% (enhanced: +16%).', source: W + 'Enhanced_gloves_of_passage' },
  { id: 'corrupted-wounds', name: 'Corrupted Wounds', kind: 'Debuff', on: 'target', durationTicks: 17,
    text: 'Target takes +20% (enhanced: +25%) bleed damage for 10 s.', source: W + 'Rend' },
  { id: 'frostblades', name: 'Frostblades', kind: 'Buff', on: 'self', durationTicks: 15,
    text: 'Melee ability hits deal flat damage equal to 24% of ability damage.', source: W + 'Dark_Shard_of_Leng' },

  // ---------------------------------------------------------------- ranged
  { id: 'searing-winds', name: 'Searing Winds', kind: 'Buff', on: 'self', durationTicks: 10, wikiId: 52801,
    text: 'Every ranged hit +20% ability damage flat. Each Rapid Fire hit extends it by 1 tick (max +8).', source: W + 'Searing_Winds' },
  { id: 'shadow-imbued', name: 'Shadow Imbued', kind: 'Buff', on: 'self', durationTicks: 50, wikiId: 52802,
    text: 'Every ranged hit +5% adrenaline (+10% with Natural Instinct). Shadow Tendrils extends it by 6 ticks. DoT ticks and self-damage do not count.', source: W + 'Shadow_Imbued' },
  { id: 'death-s-swiftness', name: "Death's Swiftness", kind: 'Buff', on: 'self', durationTicks: 50, wikiId: 19251,
    text: 'Ranged hits deal 1.5x damage (Corruption Shot DoT excluded). The buff starts 1 tick after the cast. 63 ticks with Planted Feet.', source: W + "Death's_Swiftness" },
  { id: 'greater-death-s-swiftness', name: "Greater Death's Swiftness", kind: 'Buff', on: 'self', durationTicks: 63, wikiId: 46276,
    text: 'Ranged hits deal 1.5x damage for 63 ticks. Not affected by Planted Feet.', source: W + "Greater_Death's_Swiftness" },
  { id: 'corruption-shot', name: 'Corruption Shot', kind: 'Debuff', on: 'target', durationTicks: 10, wikiId: 31986,
    text: 'DoT: 5 hits every 2 ticks at 1.0/0.8/0.6/0.4/0.2 of the initial hit. Removed by Freedom.', source: W + 'Corruption_Shot' },
  { id: 'dracolich-infusion', name: 'Dracolich infusion', kind: 'Buff', on: 'self', durationTicks: 5,
    text: '+20% ranged critical strike chance (elite: +40%) after a full Rapid Fire channel with a bow.', source: W + 'Dracolich_armour' },

  // ---------------------------------------------------------------- magic
  { id: 'anima-charged', name: 'Anima Charged', kind: 'Buff', on: 'self', durationTicks: 25, wikiId: 52778,
    text: 'Consumed by the first Sonic Wave, Greater Sonic Wave, Dragon Breath, Concentrated Blast or Greater Concentrated Blast: Sonic Wave grants 35% Flow (Greater 45%), Dragon Breath deals 260–310%, Concentrated Blast gains +10% crit chance per beam.', source: W + 'Anima_Charged' },
  { id: 'flow', name: 'Flow', kind: 'Buff', on: 'self', durationTicks: 15, wikiId: 46308,
    text: 'Next Magic ability that costs adrenaline costs 10% less. Consumed by that ability.', source: W + 'Flow' },
  { id: 'flow-charged', name: 'Flow (Anima Charged)', kind: 'Buff', on: 'self', durationTicks: 15, wikiId: 46308,
    text: 'Next Magic ability that costs adrenaline costs 35% less. Consumed by that ability.', source: W + 'Flow' },
  { id: 'greater-flow', name: 'Greater Flow', kind: 'Buff', on: 'self', durationTicks: 15, wikiId: 46309,
    text: 'Next Magic ability that costs adrenaline costs 20% less. Consumed by that ability.', source: W + 'Greater_Flow' },
  { id: 'greater-flow-charged', name: 'Greater Flow (Anima Charged)', kind: 'Buff', on: 'self', durationTicks: 15, wikiId: 46309,
    text: 'Next Magic ability that costs adrenaline costs 45% less. Consumed by that ability.', source: W + 'Greater_Flow' },
  { id: 'combust', name: 'Combust', kind: 'Debuff', on: 'target', durationTicks: 30, wikiId: 14729,
    text: 'Burn: 10 hits of 27–33% every 3 ticks. Dragon Breath deals 1.25x to combusted targets. Recasting refreshes it. Removed by Freedom.', source: W + 'Combust' },
  { id: 'corruption-blast', name: 'Corruption Blast', kind: 'Debuff', on: 'target', durationTicks: 10, wikiId: 31985,
    text: 'DoT: 5 hits every 2 ticks, decaying. Shares its cooldown with Corruption Shot.', source: W + 'Corruption_Blast' },
  { id: 'chain', name: 'Chain', kind: 'Buff', on: 'self', durationTicks: 10, wikiId: 45047,
    text: 'Next single-target Magic ability within 10 ticks is copied to the secondary targets at 0.3x (Greater Chain 0.5x).', source: W + 'Greater_Chain' },
  { id: 'concentrated-crit', name: 'Concentrated Blast crit stacks', kind: 'Buff', on: 'self', durationTicks: null, stacks: { max: 3 },
    text: '+5% critical strike chance per beam (Greater 7%; +10% more per beam when Anima Charged) for the next Magic ability. Lost on a main-hand swap.', source: W + 'Concentrated_Blast' },
  { id: 'channelled-might', name: 'Channelled Might', kind: 'Buff', on: 'self', durationTicks: 6, wikiId: 45563,
    text: '+15% critical strike damage after a full Asphyxiate channel (5 Tumeken pieces: 15 ticks, +35%).', source: W + 'Channelled_Might' },
  { id: 'sunshine', name: 'Sunshine', kind: 'Buff', on: 'self', durationTicks: 50, wikiId: 19254,
    text: 'Magic attacks deal 1.5x while inside the area (Combust, Corruption Blast, Onslaught excluded). Starts 1 tick after the cast. 63 ticks with Planted Feet (no DoT).', source: W + 'Sunshine' },
  { id: 'greater-sunshine', name: 'Greater Sunshine', kind: 'Buff', on: 'self', durationTicks: 63, wikiId: 46275,
    text: 'Magic attacks deal 1.5x while inside the area for 63 ticks. Planted Feet only removes the DoT.', source: W + 'Greater_Sunshine' },
  { id: 'tsunami', name: 'Tsunami', kind: 'Buff', on: 'self', durationTicks: 50, wikiId: 48283,
    text: 'Every Magic critical strike generates +8% adrenaline (+16% with Natural Instinct). Recasting refreshes it.', source: W + 'Tsunami' },
  { id: 'blast-infused', name: 'Blast Infused', kind: 'Buff', on: 'self', durationTicks: 10,
    text: 'Basic Magic abilities +8% base damage (blast diffusion boots after Wild Magic).', source: W + 'Blast_Infused' },

  // ---------------------------------------------------------------- necromancy
  { id: 'invoke-death', name: 'Invoke Death', kind: 'Buff', on: 'self', durationTicks: 20,
    text: 'Your next necromancy attack applies Death Mark to the target (executes it below 25% life points, 12 s).', source: W + 'Invoke_Death' },
  { id: 'invoke-lord-of-bones', name: 'Invoke Lord of Bones', kind: 'Buff', on: 'self', durationTicks: 100,
    text: 'Skeletal spirit attacks apply Shattering Bones (armour reduction) for 1 minute.', source: W + 'Invoke_Lord_of_Bones' },
  { id: 'split-soul', name: 'Split Soul', kind: 'Buff', on: 'self', durationTicks: 34,
    text: '400% of the life points Soul Split would heal is dealt to the target instead. 20.4 s.', source: W + 'Split_Soul' },
  { id: 'darkness', name: 'Darkness', kind: 'Buff', on: 'self', durationTicks: 1200,
    text: 'Aspect of Evasion: 20% chance to avoid damage. 12 minutes; only one aspect at a time.', source: W + 'Darkness' },
  { id: 'threads-of-fate', name: 'Threads of Fate', kind: 'Buff', on: 'self', durationTicks: 11,
    text: 'Single-target necromancy attacks also hit up to 4 more enemies within 4 tiles. 6.6 s.', source: W + 'Threads_of_Fate' },
  { id: 'living-death', name: 'Living Death', kind: 'Buff', on: 'self', durationTicks: 50,
    text: 'Death Skulls cooldown 17 ticks, Finger of Death 1.5x damage, Touch of Death +6% adrenaline, basic attack +2 Necrosis. Touch of Death and Death Skulls cooldowns were reset on cast.', source: W + 'Living_Death' },
  { id: 'bloated', name: 'Bloated', kind: 'Debuff', on: 'target', durationTicks: 30, wikiId: 48338,
    text: 'DoT: 10 hits of 25% of the initial hit every 3 ticks. Recasting resets it. Spreads on death. Removed by Freedom.', source: W + 'Bloat' },
  { id: 'haunted', name: 'Haunted', kind: 'Debuff', on: 'target', durationTicks: 7, wikiId: 48344,
    text: '+10% damage taken from all player sources (capped). Every hit of the commanded Vengeful Ghost refreshes it, so it lasts as long as the ghost.', source: W + 'Command_Vengeful_Ghost' },
  { id: 'spirit-skeleton-warrior', name: 'Skeleton Warrior', kind: 'Buff', on: 'self', durationTicks: 70, wikiId: 48335,
    text: 'Conjured spirit (42 s base, longer with Spirit Pact / Robes of the First Necromancer). Command Skeleton Warrior available 6 ticks after the conjure.', source: W + 'Conjure_Skeleton_Warrior' },
  { id: 'spirit-putrid-zombie', name: 'Putrid Zombie', kind: 'Buff', on: 'self', durationTicks: 70, wikiId: 48336,
    text: 'Conjured spirit. Command Putrid Zombie explodes it 4 ticks later; re-conjure at the earliest 50 ticks after the conjure.', source: W + 'Conjure_Putrid_Zombie' },
  { id: 'spirit-vengeful-ghost', name: 'Vengeful Ghost', kind: 'Buff', on: 'self', durationTicks: 70, wikiId: 48337,
    text: 'Conjured spirit. Command Vengeful Ghost makes its hits apply Haunted for the rest of its life.', source: W + 'Conjure_Vengeful_Ghost' },
  { id: 'spirit-phantom-guardian', name: 'Phantom Guardian', kind: 'Buff', on: 'self', durationTicks: 70, wikiId: 32349,
    text: 'Conjured spirit. Gains Valour when you are hit; Command Phantom Guardian (15-tick cooldown) consumes it.', source: W + 'Conjure_Phantom_Guardian' },
  { id: 'death-spark', name: 'Death Spark', kind: 'Buff', on: 'self', durationTicks: null, stacks: { max: 5 }, wikiId: 48350,
    text: 'Omni guard: 5 basic attacks ready a double-damage basic attack.', source: W + 'Death_Spark_(status)' },
  { id: 'death-essence', name: 'Death Essence', kind: 'Buff', on: 'self', durationTicks: 50,
    text: 'For 30 s Touch of Death, Finger of Death and Death Skulls immediately ready Death Spark.', source: W + 'Death_Essence' },

  // ---------------------------------------------------------------- defence / constitution
  { id: 'anticipation', name: 'Anticipation', kind: 'Buff', on: 'self', durationTicks: 17, wikiId: 14710,
    text: 'Immune to stuns for 17 ticks, damage taken -10%. Must be active before the stun lands.', source: W + 'Anticipation' },
  { id: 'freedom', name: 'Freedom', kind: 'Buff', on: 'self', durationTicks: 10, wikiId: 14711,
    text: 'Removes stuns, binds and bleeds; immune to stuns and binds for 10 ticks. The only ability usable while stunned.', source: W + 'Freedom' },
  { id: 'provoke', name: 'Provoked', kind: 'Debuff', on: 'target', durationTicks: 17, wikiId: 14712,
    text: 'Target attacks you.', source: W + 'Provoke' },
  { id: 'divert', name: 'Divert', kind: 'Buff', on: 'self', durationTicks: 10, wikiId: 45045,
    text: 'Next hit is blocked and converted to adrenaline (up to 50%, 100% with Natural Instinct). Shares its cooldown with Resonance.', source: W + 'Divert' },
  { id: 'resonance', name: 'Resonance', kind: 'Buff', on: 'self', durationTicks: 10, wikiId: 14713,
    text: 'Next hit heals instead of damaging. Shares its cooldown with Divert.', source: W + 'Resonance' },
  { id: 'preparation', name: 'Preparation', kind: 'Buff', on: 'self', durationTicks: 16, wikiId: 14714,
    text: 'Every attack received reduces the Resonance/Divert cooldown by 5 ticks. Ends if the shield is removed.', source: W + 'Preparation' },
  { id: 'devotion', name: 'Devotion', kind: 'Buff', on: 'self', durationTicks: 16, wikiId: 25028,
    text: 'Protection prayers work at 100%. Kills extend it by 8 ticks up to 32.', source: W + 'Devotion' },
  { id: 'revenge', name: 'Revenge', kind: 'Buff', on: 'self', durationTicks: 32, wikiId: 14718, stacks: { max: 10 },
    text: 'Each attack received adds a stack (max 10), +5% damage per stack. Ends if the shield is removed.', source: W + 'Revenge' },
  { id: 'reflect', name: 'Reflect', kind: 'Buff', on: 'self', durationTicks: 16, wikiId: 14716,
    text: 'Halves damage taken and reflects 50% of it.', source: W + 'Reflect' },
  { id: 'debilitate', name: 'Debilitate', kind: 'Debuff', on: 'target', durationTicks: 23, wikiId: 14717,
    text: 'Target deals 50% less damage; duration scales with the shield tier.', source: W + 'Debilitate' },
  { id: 'immortality', name: 'Immortality', kind: 'Buff', on: 'self', durationTicks: 50, wikiId: 14721,
    text: 'Damage taken -25%; a killing blow revives you with 40% life points. Ends if the shield is removed.', source: W + 'Immortality' },
  { id: 'rejuvenate', name: 'Rejuvenate', kind: 'Buff', on: 'self', durationTicks: 17, wikiId: 14720,
    text: 'Heals 2.5% max life points per tick. Shares its cooldown with Guthix\'s Blessing and Ice Asylum.', source: W + 'Rejuvenate' },
  { id: 'barricade', name: 'Barricade', kind: 'Buff', on: 'self', durationTicks: 17, wikiId: 14719,
    text: 'Blocks all damage (stuns still apply). Duration 8 + tier/10 ticks, +10% per Turtling rank, +3/+6 ticks with the Malletops totem.', source: W + 'Barricade' },
  { id: 'natural-instinct', name: 'Natural Instinct', kind: 'Buff', on: 'self', durationTicks: 34, wikiId: 19252,
    text: 'Adrenaline gains from basics and most sources are doubled (not potions, Meteor Strike, Vestments of havoc).', source: W + 'Natural_Instinct' },
  { id: 'limitless', name: 'Limitless', kind: 'Buff', on: 'self', durationTicks: 10, wikiId: 37214,
    text: 'Threshold abilities need only 15% adrenaline instead of 50% (cost stays 15%).', source: W + 'Limitless' },
  { id: 'reprisal', name: 'Reprisal', kind: 'Buff', on: 'self', durationTicks: 10, wikiId: 33650,
    text: 'Stores all damage taken for 6 s and releases it (cap 30,000). Recast outside the GCD to fire early.', source: W + 'Reprisal' },
  { id: 'transfigure', name: 'Transfigure', kind: 'Buff', on: 'self', durationTicks: 10, wikiId: 24189,
    text: 'Self-stun for 10 ticks, then heals 250% of the damage taken (cap 75% max LP).', source: W + 'Transfigure' },
  { id: 'transfigure-immunity', name: 'Transfigure stun immunity', kind: 'Buff', on: 'self', durationTicks: 25,
    text: 'Immune to stuns and binds for 25 ticks after Transfigure ends.', source: W + 'Transfigure_stun_immunity' },
  { id: 'guthix-s-blessing', name: "Guthix's Blessing", kind: 'Buff', on: 'self', durationTicks: 15, wikiId: 19253,
    text: 'Heals 8% max life points every 3 ticks (5 times). Shares its cooldown with Rejuvenate and Ice Asylum.', source: W + "Guthix's_Blessing" },
  { id: 'ice-asylum', name: 'Ice Asylum', kind: 'Buff', on: 'self', durationTicks: 36, wikiId: 28179,
    text: 'Heals up to 7% max life points every 6 ticks (6 times). Shares its cooldown with Rejuvenate and Guthix\'s Blessing.', source: W + 'Ice_Asylum' },
  { id: 'gladiator-s-rage', name: "Gladiator's Rage", kind: 'Buff', on: 'self', durationTicks: 25,
    text: '+20% damage dealt, +10% damage taken (Scripture of Ful proc).', source: W + 'Scripture_of_Ful' },

  // ---------------------------------------------------------------- special attacks (buff-granting ones)
  { id: 'blackhole', name: 'Blackhole', kind: 'Buff', on: 'self', durationTicks: 33,
    text: 'Zaros godsword special: +25% melee damage (target and you take periodic damage). Overridden by Berserk.', source: W + 'Blackhole' },
  { id: 'instability', name: 'Instability', kind: 'Buff', on: 'self', durationTicks: 50,
    text: 'Fractured Staff of Armadyl special: every Magic critical strike fires a Lightning Surge for 30 s.', source: W + 'Instability' },
  { id: 'rampage', name: 'Rampage', kind: 'Buff', on: 'self', durationTicks: 50,
    text: 'Dragon battleaxe special: +25% melee damage (and no adrenaline gain from abilities) for 30 s.', source: W + 'Rampage' },
];

export const BUFF_BY_ID = new Map(BUFFS.map((b) => [b.id, b]));
