-- Data refresh after the September 2026 rounds (audit of 9 Sep 2026): brings every stored row up to what the app
-- writes today, so the database says what the app shows. Every statement only touches rows that need it.
--
-- 1. Double Surge is an unlockable every loadout has, not a relic: the id leaves the relics list.
-- 2. Every gizmo is ancient: the stored flag is set to true wherever it was false (equipment, backpack, the legacy
--    weaponGizmos / armourGizmos arrays).
-- 3. Notes that ask for a click ("enter instance", "run md", "(click crystal)") carry requiresAction, the same rule
--    the app applies on load (src/app/core/note-actions.ts).
-- 4. Weapon switches have no keys any more: the stored weaponKeybinds are emptied.
--
-- The guide account's rows were regenerated by 0020 and need none of this; the statements are harmless on them.

-- 1. Double Surge out of the relics
update public.setups
set loadout = jsonb_set(loadout, '{relics}', coalesce((select jsonb_agg(r) from jsonb_array_elements(loadout->'relics') r where r <> '"double-surge"'::jsonb), '[]'::jsonb))
where loadout->'relics' @> '["double-surge"]'::jsonb;

-- 2. every gizmo is ancient
update public.setups
set loadout = regexp_replace(loadout::text, '"ancient": false', '"ancient": true', 'g')::jsonb
where loadout::text like '%"ancient": false%';

-- 3. notes that ask for a click get their button
update public.rotations r
set steps = (
  select jsonb_agg(
    case
      when s->>'kind' = 'note'
        and not coalesce((s->>'phase')::boolean, false)
        and not coalesce((s->>'requiresAction')::boolean, false)
        and (
          lower(s->>'note') ~ '^(\(|(in|out|base|free)\s+role:?\s*|[a-z]+ role:?\s*)*(quick-?enter|enter|rejoin|run|walk|move|step|click|destroy|start( the)? fight|tag|equip|jump|climb|leave|exit|loot|tele(port)?|dismiss|go|pick ?up|target|open|pull|interact|surge to|dive to|bd to|escape to)\M'
          or lower(s->>'note') ~ '\mclick\M'
        )
      then s || '{"requiresAction": true}'::jsonb
      else s
    end
    order by ord
  )
  from jsonb_array_elements(r.steps) with ordinality as t(s, ord)
)
where exists (
  select 1 from jsonb_array_elements(r.steps) s
  where s->>'kind' = 'note'
    and not coalesce((s->>'phase')::boolean, false)
    and not coalesce((s->>'requiresAction')::boolean, false)
    and (
      lower(s->>'note') ~ '^(\(|(in|out|base|free)\s+role:?\s*|[a-z]+ role:?\s*)*(quick-?enter|enter|rejoin|run|walk|move|step|click|destroy|start( the)? fight|tag|equip|jump|climb|leave|exit|loot|tele(port)?|dismiss|go|pick ?up|target|open|pull|interact|surge to|dive to|bd to|escape to)\M'
      or lower(s->>'note') ~ '\mclick\M'
    )
);

-- 4. no weapon keys
update public.action_bars
set setup = jsonb_set(setup, '{weaponKeybinds}', '{}'::jsonb)
where setup ? 'weaponKeybinds' and setup->'weaponKeybinds' <> '{}'::jsonb;
